spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  datasource:
    url: jdbc:mysql://localhost:3306/crud_test
    username: crud
    password: crud

  jpa:
    hibernate:
      ddl-auto: update


server:
   port: 8086